### ISSUE TITLE
README.md 번역 기여 가능한지 문의드려요.

### ISSUE THREAD

**Issue by arron86** [longcoding/moon-api-gateway#2]
**README.md 한글 번역 기여 문의**
`README.md` 한글 번역 기여가 가능한지 문의드립니다. 번역 후에 프로젝트 코드에 직접 기여도 해보고 싶습니다.

**Comment by longcoding** [comment]
Yes. You can translate it into README.korea.md and commit it.

**Comment by arron86** [comment]
@longcoding 감사합니다. 일단 첫 PR(#3)이 머지됐으니 `/ko/README.md` 경로에 이어서 작업하겠습니다. 추후에 경로, 파일명은 직접 수정 부탁드리겠습니다. 👍
