### ISSUE TITLE
README.ko.md 경로를 수정해도 될까요?

### ISSUE THREAD

**Issue by arron86** [longcoding/moon-api-gateway#5]
의견주신 것처럼 `README.ko.md` 파일을 프로젝트 루트 경로로 옮기고, `README.md` 안의 `Introduction` 챕터에 아래와 같은 내용을 추가해서 수정하려고 합니다. 
```
Read this in other languages: English, 한국어
```

PR 진행해도 될까요?

**Comment by jin-jehmi** [comment]
Yes. You can proceed as you said.

**Comment by jin-jehmi** [comment]
Close the issue.
